from ._internal.exceptions import ScyllaPyBaseError, ScyllaPyDBError

__all__ = ["ScyllaPyBaseError", "ScyllaPyDBError"]
